version: '3.10'

services:
  nginx:
    build: ./nginx
    ports: 
      - 1339:80 
    volumes:  
      - static_volume:/home/base/templates/base #app/microservice/static 
    restart: "on-failure" 

  web: 
    build: . 
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    gunicorn todo_list.wsgi:application --bind 0.0.0.0:8000" 
    volumes: 
      - .:/base 
      - static_volume:/home/base/templates/base
    image: rujulzalte/todo_app:latest 
    expose: 
      - 8000 
    restart: "on-failure"


volumes:
  media_volume:
  static_volume:
